# If true, the /team command will be overridden with the functionality of this plugin.
# This will mess with the vanilla /team command
# OPs will see both the vanilla and the plugin's subcommands mixed together.
# Datapacks and command blocks that use /team might break.
# Not recommended.
override_team_command: false

# What aspects of a team can be modified by a team owner.
# For more info see https://minecraft.wiki/w/Commands/team
modifiable_team_options:
  displayName: true
  color: true
  friendlyFire: true
  seeFriendlyInvisibles: false
  nametagVisibility: false
  deathMessageVisibility: false
  collisionRule: false
  prefix: true
  suffix: true
