# If true, the /team command will be overridden with the functionality of this plugin.
# To use the vanilla /team command, you'll have to use /minecraft:team.
override_team_command: false

# What aspects of a team can be modified by a team owner.
# For more info see https://minecraft.wiki/w/Commands/team
modifiable_team_options:
  displayName: true
  color: true
  friendlyFire: true
  seeFriendlyInvisibles: false
  nametagVisibility: false
  deathMessageVisibility: false
  collisionRule: false
  prefix: true
  suffix: true
