name: U-Teams
version: '${project.version}'
main: code.blurone.uteams.UserTeams
api-version: '1.20'
load: STARTUP
#depend: [CommandAPI]
authors: [BlurOne!]
description: A Minecraft plugin that allows users to create and handle teams without the need for op.
website: https://github.com/BlurOne-GIT/U-Teams
